[package]
name = "itch-logview"
version = "0.1.0"
authors = ["Amos Wenger <amoswenger@gmail.com>"]
edition = "2018"

[dependencies]
serde_json = "1.0.39"
colored = "1.8.0"
clap = "2.33.0"
serde = { version = "1.0.92", features = ["derive"] }
color-backtrace = "0.2.0"
chrono = "0.4.6"
